### ISSUE TITLE
Test_multiagent.py file error

### ISSUE THREAD

**Issue by lava13ratna** [utiasDSL/gym-pybullet-drones#240]
Error in **master** branch test_multiagent.py file:
Im using conda python=3.9 
torch=2.4.1 
numpy=1.23.0
ray=1.9.0
By run the given test_multiagent.py script i got some compatible issues. Can someone suggest the workable versions?
This is the error I got:
Traceback (most recent call last):
  File "/home/lavanya-drones/DroneLanding/gym_pybullet_drones/experiments/learning/test_multiagent.py", line 256, in <module>
    agent.restore(checkpoint)
  File "/home/lavanya-drones/anaconda3/envs/drone/lib/python3.9/site-packages/ray/tune/trainable.py", line 462, in restore
    self.load_checkpoint(checkpoint_path)
  File "/home/lavanya-drones/anaconda3/envs/drone/lib/python3.9/site-packages/ray/rllib/agents/trainer.py", line 1629, in load_checkpoint
    self.__setstate__(extra_data)
  File "/home/lavanya-drones/anaconda3/envs/drone/lib/python3.9/site-packages/ray/rllib/agents/trainer.py", line 2110, in __setstate__
    self.workers.local_worker().restore(state["worker"])
  File "/home/lavanya-drones/anaconda3/envs/drone/lib/python3.9/site-packages/ray/rllib/evaluation/rollout_worker.py", line 1342, in restore
    self.policy_map[pid].set_state(state)
  File "/home/lavanya-drones/anaconda3/envs/drone/lib/python3.9/site-packages/ray/rllib/policy/torch_policy.py", line 715, in set_state
    optim_state_dict = convert_to_torch_tensor(
  File "/home/lavanya-drones/anaconda3/envs/drone/lib/python3.9/site-packages/ray/rllib/utils/torch_utils.py", line 157, in convert_to_torch_tensor
    return tree.map_structure(mapping, x)
  File "/home/lavanya-drones/anaconda3/envs/drone/lib/python3.9/site-packages/tree/__init__.py", line 435, in map_structure
    [func(*args) for args in zip(*map(flatten, structures))])
  File "/home/lavanya-drones/anaconda3/envs/drone/lib/python3.9/site-packages/tree/__init__.py", line 435, in <listcomp>
    [func(*args) for args in zip(*map(flatten, structures))])
  File "/home/lavanya-drones/anaconda3/envs/drone/lib/python3.9/site-packages/ray/rllib/utils/torch_utils.py", line 151, in mapping
    tensor = torch.from_numpy(np.asarray(item))
TypeError: can't convert np.ndarray of type numpy.object_. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint64, uint32, uint16, uint8, and bool.

**Comment by lava13ratna** [comment]
solved by: pip install torch==1.11.0+cu113 torchvision==0.12.0+cu113 -f https://download.pytorch.org/whl/torch_stable.html
